baseURL = "https://mrgkanev.eu/"
languageCode = "en-us"
title = "Gabriel MrGKanev Kanev"
theme = "introduction"

PygmentsCodeFences = true
PygmentsStyle = "monokai"


[permalinks]
fixed = ":title/"
blog  = "blog/:filename/"

[params]
author = "Gabriel Kanev"
email = "contact@mrgkanev.eu"
firstname = "Gabo (Gabriel)"
tagline = "Software Engineer, Open-Source Enthusiast, Car guy"
avatar = "img/profile.jpg"
dateform = "2 Jan, 2006"
dateformfull = "2 Mon January 2006"
cachebuster = true
description = "Francesc's home page"
faviconfile = "img/favicon.ico"
highlightjs = true
lang = "en"
footertext = ""
googleAnalytics = "UA-161255919-1"
disqusShortname = "yourdiscussshortname"



# Social icons appear in introduction and contact section. Input your username only, eg "you" as it appears in "twitter.com/you"
facebook      = "mrgkanev"
linkedin      = "mrgkanev/"
twitter       = "mrgkanev"
github        = "mrgkanev"
googleplus    = ""
codepen       = ""
pinterest     = ""

showblog        = false # Show Blog section on home page
showallposts    = false # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
showlatest      = true # Show latest blog post summary
sharebuttons    = true # On post pages, show share this social buttons

showprojects    = true # Show Projects section on home page

# This is your projects section. Three images of the same dimensions will look the nicest. If images are omitted, text links will be shown.
project1link    = "https://github.com/AntiProxies"
project1img     = "img/image1.png"
project1title   = "Antiproxies"
project1desc    = "Simple to implement API for saving your website an IP at a time."

project2link    = "https://github.com/AntiProxies"
project2img     = "img/image2.png"
project2title   = "Antiproxies"
project2desc    = "Simple to implement API for saving your website an IP at a time."

project3link    = "https://github.com/AntiProxies"
project3img     = "img/image3.png"
project3title   = "Antiproxies"
project3desc    = "Simple to implement API for saving your website an IP at a time."


