[context.production.environment]
  HUGO_VERSION = "0.74.0"

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[build]
publish = "public"
command = "hugo --gc --minify"

[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.jpg" # jpg files too
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.png" # png files too
  [headers.values]
    Cache-Control = "public, max-age=604800"



[context.split1]
command = "hugo --gc --minify --enableGitInfo"
[context.split1.environment]
HUGO_VERSION = "0.74.0"
HUGO_ENV = "production"
[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
HUGO_VERSION = "0.74.0"
[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
[context.branch-deploy.environment]
HUGO_VERSION = "0.74.0"
[context.next.environment]
HUGO_ENABLEGITINFO = "true"